# Cloud Build configuration for Trading System
# This file defines the build steps for Google Cloud Build

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/trading-system:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/trading-system:latest',
      '.'
    ]
    timeout: '600s'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/trading-system:$COMMIT_SHA'
    ]
    timeout: '300s'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/trading-system:latest'
    ]
    timeout: '300s'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'trading-system',
      '--image', 'gcr.io/$PROJECT_ID/trading-system:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--concurrency', '100',
      '--max-instances', '10',
      '--min-instances', '0',
      '--port', '8080',
      '--set-env-vars', 'PORT=8080,CONFIG_FILE=config/production.ini',
      '--project', '$PROJECT_ID'
    ]
    timeout: '600s'

  # Step 4: Test the deployment
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Wait for service to be ready
        sleep 30
        
        # Get the service URL
        SERVICE_URL=$(gcloud run services describe trading-system \
          --region=us-central1 \
          --format='value(status.url)' \
          --project=$PROJECT_ID)
        
        echo "Testing deployment at: $SERVICE_URL"
        
        # Test health endpoint
        curl -f "$SERVICE_URL/health" || exit 1
        
        echo "✅ Deployment test passed!"
    timeout: '300s'

# Specify which images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/trading-system:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/trading-system:latest'

# Build configuration
options:
  # Use a larger machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Set disk size for build
  diskSizeGb: 100
  
  # Use substitution variables
  substitution_option: 'ALLOW_LOOSE'
  
  # Logging options
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1800s'  # 30 minutes

# Substitutions for variables
substitutions:
  _SERVICE_NAME: 'trading-system'
  _REGION: 'us-central1'
